Algoritmo "05_EXERCICIO_IDADE"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adriano leite
// Descrição   : Calcula os anos em questão e mostra sua idade.
// Autor(a)    : Eduardo Nathan
// Data atual  : 10/02/2021
Var
// Seção de Declarações das variáveis 
ano1, ano2: inteiro

Inicio
escreval("Em que ano você nasceu?")
leia(ano1)
escreval("Em que ano você está vendo esse algoritmo?")
leia(ano2)
escreval ("Então sua idade é: ", ano2 - ano1)


Fimalgoritmo